apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cloudness-http
  namespace: cloudness
  labels:
    identifier: cloudness-http
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
      sectionName: web
      kind: Gateway

  hostnames:
    - {{ .ServiceDomain.Domain }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: cloudness
          namespace: cloudness
          port: 8000
