name: ðŸž Bug Report
description: "File a new bug report."
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **Please ensure you are using the latest version of Cloudness before submitting an issue, as the bug may have already been fixed in a recent update.**

        Thanks for taking the time to fill out this bug report! The more details you provide, the faster we can help.

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Message and Logs
      description: Provide any error messages or relevant log output.
      render: shell
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step guide to reproduce the issue. Be as detailed as possible.
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
    validations:
      required: true

  - type: input
    attributes:
      label: Cloudness Version
      description: Run `cloudness version` or check your deployment. Found in the UI footer or logs.
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Installation Type
      description: How is Cloudness deployed?
      options:
        - Self-hosted (Kubernetes)
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: Kubernetes Version
      description: Run `kubectl version --short` and provide the server version.
      placeholder: "v1.28.0"
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Kubernetes Distribution
      description: What Kubernetes distribution are you using?
      options:
        - k3s
        - k8s (vanilla)
        - EKS (AWS)
        - GKE (Google)
        - AKS (Azure)
        - minikube
        - kind
        - Rancher
        - OpenShift
        - Other
    validations:
      required: false

  - type: input
    attributes:
      label: Operating System
      description: Run `cat /etc/os-release` or provide your OS version.
      placeholder: "Ubuntu 22.04"
    validations:
      required: false

  - type: input
    attributes:
      label: Browser (if UI issue)
      description: Provide browser name and version if this is a UI-related issue.
      placeholder: "Chrome 120"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other relevant information, screenshots, or context about the issue.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported.
          required: true
        - label: I am using the latest version of Cloudness (or have noted my version above).
          required: true
        - label: I have provided all the information needed to reproduce this issue.
          required: true
