name: ✨ Feature Request
description: "Suggest an idea or enhancement for Cloudness."
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please fill out the details below to help us understand your request.

  - type: textarea
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Be as detailed as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Feature Area
      description: What area of Cloudness does this relate to?
      options:
        - Deployment / CI/CD
        - UI / Dashboard
        - CLI
        - Authentication / Authorization
        - Templates
        - Kubernetes Integration
        - Database / Storage
        - Logging / Monitoring
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would benefit you and others.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, mockups, screenshots, or examples about the feature request.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested.
          required: true
        - label: I would be willing to help implement this feature.
          required: false
