// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package shared

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/cloudness-io/cloudness/app/request"
import "context"
import "fmt"
import "strings"
import "github.com/cloudness-io/cloudness/app/utils/routes"

func getBaseUrl(ctx context.Context) string {
	baseUrl, _ := request.HostDomainUrlFrom(ctx)
	tenant, ok := request.TenantFrom(ctx)
	if !ok {
		return baseUrl
	}
	baseUrl = fmt.Sprintf("%s/team/%d", baseUrl, tenant.UID)

	project, ok := request.ProjectFrom(ctx)
	if !ok {
		return baseUrl
	}
	baseUrl = fmt.Sprintf("%s/project/%d", baseUrl, project.UID)

	environment, ok := request.EnvironmentFrom(ctx)
	if !ok {
		return baseUrl
	}
	//custom logic to add environment only if the current route is any application sub route
	currUrl, _ := request.CurrentFullUrlFrom(ctx)
	if routes.HasApplicationRoute(currUrl, environment) {
		baseUrl = fmt.Sprintf("%s/environment/%d", baseUrl, environment.UID)
	}

	application, ok := request.ApplicationFrom(ctx)
	if !ok {
		return baseUrl
	}
	baseUrl = fmt.Sprintf("%s/application/%d", baseUrl, application.UID)

	//	deployment, ok := request.DeploymentFrom(ctx)
	//	if !ok {
	//		return baseUrl
	//	}

	//	baseUrl = fmt.Sprintf("%s/deployment/%d", baseUrl, deployment.UID)
	return baseUrl
}

func formatedBaseUrl(ctx context.Context) string {
	baseUrl := getBaseUrl(ctx)
	if strings.HasSuffix(baseUrl, "/") {
		return baseUrl
	}
	return baseUrl + "/"
}

func BaseUrl() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head hx-head=\"re-eval\"><base href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(formatedBaseUrl(ctx))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/web/views/shared/head_url.templ`, Line: 58, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
