// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/cloudness-io/cloudness/app/auth/authn"
	"github.com/cloudness-io/cloudness/app/bootstrap"
	"github.com/cloudness-io/cloudness/app/controller/application"
	"github.com/cloudness-io/cloudness/app/controller/auth"
	"github.com/cloudness-io/cloudness/app/controller/deployment"
	"github.com/cloudness-io/cloudness/app/controller/environment"
	"github.com/cloudness-io/cloudness/app/controller/favorite"
	githubapp2 "github.com/cloudness-io/cloudness/app/controller/githubapp"
	gitpublic2 "github.com/cloudness-io/cloudness/app/controller/gitpublic"
	"github.com/cloudness-io/cloudness/app/controller/instance"
	"github.com/cloudness-io/cloudness/app/controller/logs"
	"github.com/cloudness-io/cloudness/app/controller/project"
	server2 "github.com/cloudness-io/cloudness/app/controller/server"
	"github.com/cloudness-io/cloudness/app/controller/template"
	"github.com/cloudness-io/cloudness/app/controller/tenant"
	"github.com/cloudness-io/cloudness/app/controller/user"
	"github.com/cloudness-io/cloudness/app/controller/variable"
	"github.com/cloudness-io/cloudness/app/controller/volume"
	"github.com/cloudness-io/cloudness/app/pipeline/agent"
	"github.com/cloudness-io/cloudness/app/pipeline/canceler"
	manager2 "github.com/cloudness-io/cloudness/app/pipeline/manager"
	"github.com/cloudness-io/cloudness/app/pipeline/manager/client"
	"github.com/cloudness-io/cloudness/app/pipeline/scheduler"
	"github.com/cloudness-io/cloudness/app/pipeline/triggerer"
	"github.com/cloudness-io/cloudness/app/router"
	server3 "github.com/cloudness-io/cloudness/app/server"
	"github.com/cloudness-io/cloudness/app/services"
	"github.com/cloudness-io/cloudness/app/services/background"
	"github.com/cloudness-io/cloudness/app/services/cleanup"
	"github.com/cloudness-io/cloudness/app/services/config"
	"github.com/cloudness-io/cloudness/app/services/dns"
	"github.com/cloudness-io/cloudness/app/services/githubapp"
	"github.com/cloudness-io/cloudness/app/services/gitpublic"
	"github.com/cloudness-io/cloudness/app/services/manager"
	"github.com/cloudness-io/cloudness/app/services/proxy"
	"github.com/cloudness-io/cloudness/app/services/schema"
	"github.com/cloudness-io/cloudness/app/services/spec"
	"github.com/cloudness-io/cloudness/app/sse"
	"github.com/cloudness-io/cloudness/app/store/database"
	"github.com/cloudness-io/cloudness/cli/operations/server"
	"github.com/cloudness-io/cloudness/job"
	"github.com/cloudness-io/cloudness/lock"
	"github.com/cloudness-io/cloudness/logstream"
	"github.com/cloudness-io/cloudness/pubsub"
	"github.com/cloudness-io/cloudness/store/database/dbtx"
	"github.com/cloudness-io/cloudness/types"

	_ "github.com/lib/pq"

	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func initSystem(ctx context.Context, config2 *types.Config) (*server.System, error) {
	databaseConfig := server.ProvideDatabaseConfig(config2)
	db, err := database.ProvideDatabase(ctx, databaseConfig)
	if err != nil {
		return nil, err
	}
	accessorTx := dbtx.ProvideAccessorTx(db)
	transactor := dbtx.ProvideTransactor(accessorTx)
	instanceStore := database.ProvideInstanceStore(db)
	serverStore := database.ProvideServerStore(db)
	principalStore := database.ProvideUserStore(db)
	service := dns.ProvideDNSService()
	proxyService := proxy.ProvideProxyService()
	configService := config.ProvideConfigService(config2, instanceStore)
	k8sManager := manager.ProvideK8sManager(configService)
	managerFactory := manager.ProvideManagerFactory(k8sManager)
	controller := instance.ProvideController(transactor, instanceStore, serverStore, principalStore, service, proxyService, managerFactory)
	serverController := server2.ProvideController(transactor, configService, service, proxyService, serverStore, instanceStore, managerFactory)
	userController := user.ProvideController(transactor, principalStore)
	tenantStore := database.ProvideTenantStore(db)
	tenantMembershipStore := database.ProvideTenantMembershipStore(db)
	schemaService := schema.ProviderSchemaService()
	githubAppStore := database.ProvideGithubAppStore(db)
	privateKeyStore := database.ProvidePrivateKeyStore(db)
	githubappService := githubapp.ProvideService(transactor, githubAppStore, privateKeyStore)
	gitpublicService := gitpublic.ProvideGitpublicService()
	specService := spec.ProvideSpecService(githubappService, gitpublicService)
	applicationStore := database.ProvideApplicationStore(db)
	metricsStore := database.ProvideMetricsStore(db)
	variableStore := database.ProvideVariableStore(db)
	variableController := variable.ProvideController(variableStore)
	gitpublicController := gitpublic2.ProvideController(gitpublicService)
	volumeStore := database.ProvideVolumeStore(db)
	volumeController := volume.ProvideController(configService, volumeStore)
	deploymentStore := database.ProvideDeploymentStore(db)
	lockConfig := server.ProvideLockConfig(config2)
	universalClient, err := server.ProvideRedis(config2)
	if err != nil {
		return nil, err
	}
	mutexManager := lock.ProvideMutexManager(lockConfig, universalClient)
	schedulerScheduler, err := scheduler.ProvideScheduler(deploymentStore, mutexManager)
	if err != nil {
		return nil, err
	}
	pubsubConfig := server.ProvidePubSubConfig(config2)
	pubSub := pubsub.ProvidePubSub(pubsubConfig, universalClient)
	streamer := sse.ProvideEventStreamer(pubSub)
	cancelerCanceler := canceler.ProvideCanceler(deploymentStore, streamer, schedulerScheduler)
	triggererTriggerer := triggerer.ProvideTriggerer(transactor, applicationStore, deploymentStore, schedulerScheduler, cancelerCanceler)
	applicationController := application.ProvideController(transactor, configService, schemaService, specService, applicationStore, metricsStore, serverController, variableController, gitpublicController, volumeController, triggererTriggerer, cancelerCanceler, managerFactory)
	environmentStore := database.ProvideEnvironmentStore(db)
	environmentController := environment.ProvideController(transactor, applicationController, volumeController, environmentStore)
	projectStore := database.ProvideProjectStore(db)
	projectMembershipStore := database.ProvideProjectMembershipStore(db)
	projectController := project.ProviderController(transactor, configService, userController, environmentController, projectStore, projectMembershipStore, tenantMembershipStore, streamer)
	tenantController := tenant.ProviderController(transactor, configService, tenantStore, tenantMembershipStore, userController, projectController)
	tokenStore := database.ProvideTokenStore(db)
	authSettingsStore := database.ProvideAuthSettingStore(db)
	authController := auth.ProvideController(transactor, controller, userController, tenantController, tokenStore, authSettingsStore)
	templateStore := database.ProvideTemplateStore(db)
	templateController := template.ProvideController(templateStore, applicationController, schemaService, triggererTriggerer)
	bootstrapBootstrap := bootstrap.ProvideBootstrap(config2, controller, serverController, authController, userController, templateController)
	authenticator := authn.ProvideAuthenticator(config2, principalStore, tokenStore)
	githubappController := githubapp2.ProvideController(githubappService)
	deploymentController := deployment.ProvideController(deploymentStore)
	logStore := database.ProvideLogStore(db)
	logStream := logstream.ProvideLogStream()
	logsController := logs.ProvideController(logStore, logStream)
	favoriteStore := database.ProvideFavoriteStore(db)
	favoriteController := favorite.ProvideController(favoriteStore)
	webHandler := router.ProvideWebHandler(ctx, config2, authenticator, controller, serverController, userController, tenantController, projectController, environmentController, authController, githubappController, gitpublicController, applicationController, variableController, deploymentController, logsController, volumeController, templateController, favoriteController)
	routerRouter := router.ProvideRouter(webHandler)
	serverServer := server3.ProvideServer(config2, routerRouter)
	runnerManager := manager2.ProvideRunnerManager(schedulerScheduler, serverStore, applicationStore, deploymentStore, volumeStore, logStore, metricsStore, variableController, configService, githubappService, streamer, logStream)
	runnerClient := client.ProvideRunnerClient(runnerManager)
	agentAgent := agent.ProvideAgent(runnerClient, managerFactory)
	store := database.ProvideJobStore(db)
	executor := job.ProvideExecutor(store, pubSub)
	jobScheduler, err := job.ProvideScheduler(store, executor, mutexManager, pubSub)
	if err != nil {
		return nil, err
	}
	cleanupService := cleanup.ProvideService(jobScheduler, executor, serverStore, tenantStore, projectStore, environmentStore, applicationStore, volumeStore, managerFactory)
	servicesServices := services.ProvideServices(jobScheduler, cleanupService)
	backgroundService := background.ProvideService(mutexManager)
	system := server.NewSystem(bootstrapBootstrap, serverServer, agentAgent, servicesServices, backgroundService)
	return system, nil
}
