// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package vinstance

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/cloudness-io/cloudness/app/web/views/shared"
import "github.com/cloudness-io/cloudness/types"
import "github.com/cloudness-io/cloudness/app/web/views/xdata"
import "github.com/cloudness-io/cloudness/app/web/views/components/icons"

func Registry(instance *types.Instance) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex items-center gap-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Icon(icons.SourceRegistryIcon, "size-6").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h3>Registry</h3></div><form class=\"flex flex-col gap-5 w-full mt-2\" x-data=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(xdata.ToFormData(instance))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/web/views/components/vinstance/registry.templ`, Line: 20, Col: 38}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" x-clock>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.CheckBox(&shared.CheckBoxProps{
				Name:    "registry_enabled",
				Label:   "Enable Registry",
				Tooltip: "Enabled by default untill 3rd party registry integration is added",
				Attrs: templ.Attributes{
					"x-model.boolean": "form.registry_enabled",
					"x-bind:checked":  "form.registry_enabled === 'true'",
					"@change":         "form.registry_enabled = $el.checked ? 'true' : 'false'",
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Input(&shared.InputProps{
				Name:        "registry_size",
				Label:       "Registry Volume Size",
				Tooltip:     "Size of the volume in GB, cannot be downsized",
				Type:        "number",
				Placeholder: "1",
				Required:    true,
				Attrs: templ.Attributes{
					"x-model.number":  "form.registry_size",
					"x-bind:min":      instance.RegistrySize,
					"x-bind:disabled": "form.registry_enabled !== 'true'",
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.CheckBox(&shared.CheckBoxProps{
				Name:    "registry_mirror_enabled",
				Label:   "Enable Mirror Registry",
				Tooltip: "Mirror registry to store base images used in building, so you do not hit the docker hub rate limit",
				Attrs: templ.Attributes{
					"x-model.boolean": "form.registry_mirror_enabled",
					"x-bind:checked":  "form.registry_mirror_enabled === 'true'",
					"@change":         "form.registry_mirror_enabled = $el.checked ? 'true' : 'false'",
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Input(&shared.InputProps{
				Name:        "registry_mirror_size",
				Label:       "Mirror Registry Volume Size",
				Tooltip:     "Size of the volume in GB, cannot be downsized",
				Type:        "number",
				Placeholder: "1",
				Attrs: templ.Attributes{
					"x-model.number":  "form.registry_mirror_size",
					"min":             instance.RegistryMirrorSize,
					"x-bind:disabled": "form.registry_mirror_enabled !== 'true'",
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.UpdateDiv("/settings/registry").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</form><!--\n\t\t<div class=\"flex flex-col gap-2\">\n\t\t\tif instance.RegistryEnabled {\n\t\t\t\t<h4>Registry Status</h4>\n\t\t\t\t<div>Registry statis goes here </div>\n\t\t\t}\n\t\t\tif instance.RegistryProxyEnabled {\n\t\t\t\t<h4>Proxy Registry Status</h4>\n\t\t\t\t<div>Proxy Registry statis goes here </div>\n\t\t\t}\n\t\t</div>\n\t\t-->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = shared.PageView(&shared.PageViewProps{
			ActiveName: InstanceNavRegistry,
			Options:    getInstanceNav(),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
