// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package vserver

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	serverCtrl "github.com/cloudness-io/cloudness/app/controller/server"
	"github.com/cloudness-io/cloudness/app/web/views/components/icons"
	"github.com/cloudness-io/cloudness/app/web/views/shared"
	"github.com/cloudness-io/cloudness/app/web/views/xdata"
	"github.com/cloudness-io/cloudness/types"
)

func limits(server *types.Server) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex items-center gap-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.Icon(icons.LimitsIcon, "icon-xl").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h3>Server Limits</h3></div><form class=\"flex flex-col place-items-baseline mt-4 gap-2\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(xdata.ToFormData(&serverCtrl.ServerLimitsUpdateModel{
			SupportsOnlineExpansion: server.VolumeSupportsOnlineExpansion,
			MinVolumeSize:           server.VolumeMinSize,
		}))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/web/views/components/vserver/limits.templ`, Line: 21, Col: 5}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" x-clock hx-push-url=\"false\"><h4>Volume Limits</h4>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.CheckBox(&shared.CheckBoxProps{
			Name:    "supports_online_expansion",
			Label:   "Allows Online Expansion",
			Tooltip: "When unchecked, Volumes to be unmounted from pod before resizing, since many cloud providers do not support volumes online expansion in place.",
			Attrs: templ.Attributes{
				"x-model.boolean": "form.supports_online_expansion",
				"x-bind:checked":  "form.supports_online_expansion === 'true'",
				"@change":         "form.supports_online_expansion = $el.checked ? 'true' : 'false'",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.Input(&shared.InputProps{
			Name:  "min_volume_size",
			Label: "Min Volume Size",
			Tooltip: `Minimum size of the volume in GB, this is to handle the limitations of the underlying cloud
				providers if any. E.g. linode cannot have volumes less than 10GB.`,
			Type:        "number",
			Placeholder: "1",
			Required:    true,
			Attrs: templ.Attributes{
				"x-model.number": "form.min_volume_size",
				"x-bind:min":     "1",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.UpdateDiv("/settings/server/limits").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
