// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package vserver

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/cloudness-io/cloudness/app/web/views/shared"
	"github.com/cloudness-io/cloudness/app/web/views/xdata"
	"github.com/cloudness-io/cloudness/types"

	serverCtrl "github.com/cloudness-io/cloudness/app/controller/server"
	"github.com/cloudness-io/cloudness/app/web/views/components/icons"
	"github.com/cloudness-io/cloudness/types/enum"
)

func networkSetting(server *types.Server) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex items-center gap-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.Icon(icons.NetworkSectionIcon, "icon-lg").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h3>Network Settings</h3></div><form class=\"flex flex-col place-items-baseline mt-4 gap-2\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(xdata.ToFormData(&serverCtrl.ServerNetworkUpdateModel{
			WildCardDomain: server.WildCardDomain,
			IPV4:           server.IPV4,
			DNSProxy:       server.DNSProxy,
			ProxyAuth:      server.ProxyAuthKey,
		}))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/web/views/components/vserver/network.templ`, Line: 25, Col: 8}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" x-clock hx-push-url=\"false\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.Input(&shared.InputProps{
			Name:        "wildcard_domain",
			Label:       "Wildcard Domain",
			Placeholder: "https://example.com",
			Tooltip:     `A wildcard domain allows you to receive a randomly generated domain for your new application. For instance, if you set https://example.com as your wildcard domain, your applications will receive domains like https://randomId.example.com`,
			Attrs: templ.Attributes{
				"x-model": "form.wildcard_domain",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"max-w-sm sm:max-w-md md:max-w-lg w-full\" x-show=\"initial.wildcard_domain !== '' && form.wildcard_domain !== initial.wildcard_domain\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.WarningAlert(
			"Changing you wildcard domain will cause unexpected behavior",
			"Be very caucious before proceeding",
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.Input(&shared.InputProps{
			Name:    "ipv4",
			Label:   "Servers's IPV4",
			Tooltip: `Public IPV4 of the server`,
			Value:   server.IPV4,
			Attrs: templ.Attributes{
				"x-model": "form.ipv4",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.Dropdown(&shared.DropdownProps{
			Name:          "dns_proxy",
			Label:         "DNS Proxy",
			Tooltip:       "If your domain in behind a DNS proxy",
			Options:       enum.ServerProxysStr,
			DropdownClass: "capitalize",
			Attrs: templ.Attributes{
				"x-model":   "form.dns_proxy",
				":disabled": "form.wildcard_domain === ''",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.Input(&shared.InputProps{
			Name:  "proxy_auth",
			Label: "Proxy API Key",
			Tooltip: `Proxy API token for the proxy service, This is used to generate/renew SSL certificate thorugh
			DNS challenge, API token should have access to Zone DNS Edit`,
			Disclaimer: `<span>How to create API token? Please refer to <a class="link"
			href="https://developers.cloudflare.com/fundamentals/api/get-started/create-token" target="_blank">Cloudflare API Tokens</a></span>`,
			Password: true,
			Attrs: templ.Attributes{
				"x-model":   "form.proxy_auth",
				":disabled": "form.wildcard_domain === ''",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = shared.UpdateDiv("/settings/server/network").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</form><div class=\"flex items-center gap-1\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
