apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Identifier }}-sa
  namespace: {{ .Namespace }}
  labels:
    identifier: {{ .Identifier }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Identifier }}-role
  namespace: {{ .Namespace }}
  labels:
    identifier: {{ .Identifier }}
rules:
- apiGroups: [""] # Core API group
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Identifier }}-rolebinding
  namespace: {{ .Namespace }}
  labels:
    identifier: {{ .Identifier }}
subjects:
- kind: ServiceAccount
  name: {{ .Identifier }}-sa
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Identifier }}-role

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Identifier }}
  namespace: {{ .Namespace }}
  labels:
    identifier: {{ .Identifier }}
data:
  {{- range $key, $value := .Variables }}
  {{ $key }}: {{ $value }}
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Identifier }}
  namespace: {{ .Namespace }}
  labels:
    identifier: {{ .Identifier }}
type: Opaque
data:
  {{- range $key, $value := .Secrets }}
  {{ $key }}: {{ $value }}
  {{ end }}