apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Namespace }}
  labels:
    apiserver-proxy.networking.gardener.cloud/inject: "disable"
    app.kubernetes.io/managed-by: cloudness

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Identifier }}-sa
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Identifier }}
    app.kubernetes.io/instance: {{ .Identifier }}
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/managed-by: cloudness

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Identifier }}-role
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Identifier }}
    app.kubernetes.io/instance: {{ .Identifier }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: cloudness
rules:
- apiGroups: [""] # Core API group
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Identifier }}-rolebinding
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Identifier }}
    app.kubernetes.io/instance: {{ .Identifier }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: cloudness
subjects:
- kind: ServiceAccount
  name: {{ .Identifier }}-sa
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Identifier }}-role

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Identifier }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Identifier }}
    app.kubernetes.io/instance: {{ .Identifier }}
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: cloudness
data:
  {{- range $key, $value := .Variables }}
  {{ $key }}: {{ $value }}
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Identifier }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Identifier }}
    app.kubernetes.io/instance: {{ .Identifier }}
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: cloudness
type: Opaque
data:
  {{- range $key, $value := .Secrets }}
  {{ $key }}: {{ $value }}
  {{ end }}

# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: {{ .Identifier }}-netpol
#   namespace: {{ .Namespace }}
#   labels:
#     app.kubernetes.io/name: {{ .Identifier }}
#     app.kubernetes.io/instance: {{ .Identifier }}
#     app.kubernetes.io/component: network-policy
#     app.kubernetes.io/managed-by: cloudness
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/name: {{ .Identifier }}
#       app.kubernetes.io/instance: {{ .Identifier }}
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   # Allow ingress from anywhere within the namespace
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: {{ .Namespace }}
#   # Allow ingress from HTTP gateway (kgateway.dev)
#   - from:
#     - namespaceSelector: {}
#       podSelector:
#         matchLabels:
#           app.kubernetes.io/name: kgateway
#   egress:
#   # Allow DNS resolution
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: kube-system
#     ports:
#     - protocol: UDP
#       port: 53
#     - protocol: TCP
#       port: 53
#   # Allow egress within the same namespace only
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: {{ .Namespace }}
#   # Block access to Kubernetes API server (10.43.0.1 or 10.96.0.1 typically)
#   # The above rules implicitly deny everything else including API server access
