{{ if .ServiceDomain }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Identifier }}-http
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Identifier }}
    app.kubernetes.io/instance: {{ .Identifier }}
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: cloudness
spec:
  parentRefs:
  {{ if .ServiceDomain.Websecure }}
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: cloudness-wildcard-listener
      namespace: kgateway-system
      sectionName: cloudness-wildcard-listener-section
  {{ else }}
    - kind: Gateway
      name: cloudness-gateway
      namespace: kgateway-system
      sectionName: web
  {{ end }}

  hostnames:
    - {{ .ServiceDomain.Domain }}

  rules:
     - matches:
        - path:
            type: PathPrefix
            value: /

       backendRefs:
        - name: {{ $.PrivateDomain }}
          namespace: {{ $.Namespace }}
          port: {{ .ServiceDomain.Port }}
{{ end }}